spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/redis-session-store_db
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/redis-session-store_db
    locations: db.migration
  redis:
    host: localhost
    port: 6379